server:
  port: 8185

spring:
  profiles:
    active: test
  messages:
    basename: messages
    encoding: UTF-8

  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    mode: LEGACYHTML5
    content-type: text/html
    encoding: UTF-8

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: oracle
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: nanumdb
    password: 1234
    sql-script-encoding: UTF-8
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

flyway:
  enabled: true
  baseline-version: 1
  baseline-on-migrate: true

logging:
  file: log/nanum.log
  pattern:
    console: '%clr(%-5p %d{HH:mm:ss.SSS}) (%F:%L\) - %msg%n'
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p) %c{1}[%M]%L - %msg%n'

